// <auto-generated />
using System;
using InsiderOUT.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insider_OUT.Server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260223162334_AddTokenTimestamps")]
    partial class AddTokenTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Incidents.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActivityContent");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActivityDate");

                    b.Property<int>("ActivityEntityId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityEntityId");

                    b.Property<string>("ActivityEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ActivityEntityType");

                    b.Property<int?>("ActivityUserId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityUserId");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityUserId");

                    b.HasIndex("ActivityEntityId", "ActivityEntityType")
                        .HasDatabaseName("IX_Activities_Entity");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Incidents.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IncidentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("IncidentAgent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IncidentAgent");

                    b.Property<int?>("IncidentAssignedUserId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentAssignedUserId");

                    b.Property<DateTime>("IncidentCreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IncidentCreatedDate");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IncidentDescription");

                    b.Property<string>("IncidentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IncidentStatus");

                    b.Property<int?>("IncidentTiedSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentTiedSubjectId");

                    b.Property<string>("IncidentTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IncidentTitle");

                    b.Property<int>("IncidentTokenId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentTokenId");

                    b.Property<string>("IncidentTokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IncidentTokenType");

                    b.Property<DateTime>("IncidentUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IncidentUpdatedDate");

                    b.HasKey("IncidentId");

                    b.HasIndex("IncidentAssignedUserId")
                        .HasDatabaseName("IX_Incidents_AssignedUserId");

                    b.HasIndex("IncidentTiedSubjectId")
                        .HasDatabaseName("IX_Incidents_TiedSubjectId");

                    b.HasIndex("IncidentTokenId")
                        .HasDatabaseName("IX_Incidents_TokenId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Profiles.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubjectDepartment");

                    b.Property<string>("SubjectEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SubjectEmail");

                    b.Property<string>("SubjectFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubjectFirstName");

                    b.Property<string>("SubjectLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubjectLastName");

                    b.Property<string>("SubjectPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SubjectPhone");

                    b.Property<int>("SubjectRiskScore")
                        .HasColumnType("int")
                        .HasColumnName("SubjectRiskScore");

                    b.Property<string>("SubjectRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubjectRole");

                    b.HasKey("SubjectId");

                    b.HasIndex("SubjectRiskScore")
                        .HasDatabaseName("IX_Subjects_RiskScore");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Profiles.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserDepartment");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UserEmail");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserFirstName");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserLastName");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserPhone");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Tokens.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DocumentLocation");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DocumentName");

                    b.Property<int>("DocumentTokenId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentTokenId");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentTokenId")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Tokens.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmailSubject");

                    b.Property<int>("EmailTokenId")
                        .HasColumnType("int")
                        .HasColumnName("EmailTokenId");

                    b.HasKey("EmailId");

                    b.HasIndex("EmailTokenId")
                        .IsUnique();

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Tokens.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("TokenSeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TokenSeverity");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TokenType");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenType")
                        .HasDatabaseName("IX_Tokens_Type");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Incidents.Activity", b =>
                {
                    b.HasOne("Insider_OUT.Server.Data.Models.Profiles.User", "User")
                        .WithMany()
                        .HasForeignKey("ActivityUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Incidents.Incident", b =>
                {
                    b.HasOne("Insider_OUT.Server.Data.Models.Profiles.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("IncidentAssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Insider_OUT.Server.Data.Models.Profiles.Subject", "TiedSubject")
                        .WithMany()
                        .HasForeignKey("IncidentTiedSubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Insider_OUT.Server.Data.Models.Tokens.Token", "Token")
                        .WithMany()
                        .HasForeignKey("IncidentTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("TiedSubject");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Tokens.Document", b =>
                {
                    b.HasOne("Insider_OUT.Server.Data.Models.Tokens.Token", "Token")
                        .WithOne("Document")
                        .HasForeignKey("Insider_OUT.Server.Data.Models.Tokens.Document", "DocumentTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Tokens.Email", b =>
                {
                    b.HasOne("Insider_OUT.Server.Data.Models.Tokens.Token", "Token")
                        .WithOne("Email")
                        .HasForeignKey("Insider_OUT.Server.Data.Models.Tokens.Email", "EmailTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Insider_OUT.Server.Data.Models.Tokens.Token", b =>
                {
                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
